/* Generated by aok_mksignames.c -- do not edit.
 *
 * Replaces dash's own mksignames.c, which is GPL-2+ and is not
 * part of this tree. See src/aok_mksignames.c for why.
 *
 * BSD-3-Clause, as the rest of dash.
 */

#include <signal.h>

/* A translation list so we can be polite to our users. */
const char *const signal_names[NSIG + 1] = {
    "EXIT",
    "HUP",
    "INT",
    "QUIT",
    "ILL",
    "TRAP",
    "ABRT",
    "EMT",
    "FPE",
    "KILL",
    "BUS",
    "SEGV",
    "SYS",
    "PIPE",
    "ALRM",
    "TERM",
    "URG",
    "STOP",
    "TSTP",
    "CONT",
    "CHLD",
    "TTIN",
    "TTOU",
    "IO",
    "XCPU",
    "XFSZ",
    "VTALRM",
    "PROF",
    "WINCH",
    "INFO",
    "USR1",
    "USR2",
    (char *)0x0
};
